import fs from 'node:fs/promises';
import path from 'node:path';
import type { StorageProvider, StoredObject, UploadParams } from './StorageProvider.js';

/**
 * Development driver: keeps artwork binaries on local disk.
 *
 * Deliberately implements the exact same contract as the Supabase driver,
 * including bucket semantics, so development and production exercise identical
 * application code paths.
 */
export class LocalStorageProvider implements StorageProvider {
  readonly driver = 'local' as const;
  readonly bucket: string;
  private readonly rootDir: string;

  constructor(rootDir: string, bucket: string) {
    this.rootDir = path.resolve(rootDir);
    this.bucket = bucket;
  }

  private resolve(object: StoredObject): string {
    const target = path.resolve(this.rootDir, object.bucket, object.path);
    const bucketRoot = path.resolve(this.rootDir, object.bucket);
    // Defence in depth: even though storage keys are always generated by the
    // server, never let one escape its bucket directory.
    if (target !== bucketRoot && !target.startsWith(`${bucketRoot}${path.sep}`)) {
      throw new Error('Caminho de armazenamento inválido.');
    }
    return target;
  }

  async upload({ path: objectPath, body }: UploadParams): Promise<StoredObject> {
    const object: StoredObject = { bucket: this.bucket, path: objectPath };
    const target = this.resolve(object);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, body);
    return object;
  }

  async download(object: StoredObject): Promise<Buffer> {
    return fs.readFile(this.resolve(object));
  }

  async remove(object: StoredObject): Promise<void> {
    await fs.rm(this.resolve(object), { force: true });
  }

  async exists(object: StoredObject): Promise<boolean> {
    try {
      await fs.access(this.resolve(object));
      return true;
    } catch {
      return false;
    }
  }
}
